### ISSUE TITLE
Folders created as root after first containers start

### ISSUE THREAD

**Issue by mariorguezari** [AriHealth/elk-secure-docker-compose#2]
## Expected Behavior

Containers running smoothly after first docker-compose up.

## Actual Behavior

Container logs in elasticsearch show: [2019-05-29T23:08:09,866][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
 org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to create node environment
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:140) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127) ~[elasticsearch-6.4.2.jar:6.4.2]...

## Steps to Reproduce the Problem

  1. docker-compose up -d
  1. docker-compose logs --details elasticsearch

## Specifications

  - Version: Docker version 18.09.6, build 481bc77
  - Platform: Ubuntu xenial running in Vagrant

**Comment by mariorguezari** [comment]
Some folders are owned by root, and the problem may be caused by permission restrictions (logging files cannot be writen, for example).

Manual solution: in case of vagrant, changing the owner to the vagrant user makes it:

sudo chown -R vagrant:vagrant elk

The accepted solution to the issue could be an automatization of this.

**Comment by carloscaverobarca** [comment]
But is this related to #1? Or is another different problem?

**Comment by mariorguezari** [comment]
I guess they are two different issues:
- #1 is related to paths
- #2 is related to permissions

Although probably the solution will solve both of them.
